### ISSUE TITLE
How do I launch ReShade?

### ISSUE THREAD

**Issue by Belugaking** [kevinlekiller/reshade-steam-proton#4]
The script doesn't really explain how to launch it and it looks like that on windows it's shift + f2 by default but it does not seem to work.

**Comment by kevinlekiller** [comment]
When you start the game, a message will show up to show that it's loaded, it will show the key you need to press to access the interface, by default it's the Home key.

If the message doesn't show up, it's usually because the wrong ReShade dll or dll name was used.

Also, sometimes ReShade doesn't support the game engine (RPG Maker games for example) or graphics API (Pre DirectX 8 games for example).

If you list the game in particular, I can try to look it up or test it if I own it.

**Comment by DieuDeGlace** [comment]
Elden ring doesnt even show the little message at the top. Ive tried just about everything and it still refuses to work

**Comment by kevinlekiller** [comment]
Elden ring uses Directx 12, maybe it needs the dll to be named d3d12 ?

**Comment by DieuDeGlace** [comment]
seemingly that is not it; however, i did find a fix. Using an older reshade version apparently works. though if i wanna use the new reshade version ill try it.

**Comment by TheKarion** [comment]
I'm getting the same issue with Elden Ring, no gui menu and i dont think its working. I put the .ini preset in the game directory and tried to link it to the script but i dont think that worked/

**Comment by humanplayer2** [comment]
I'm setting up reshaders for the first time on Linux---for Elden Ring---having done it only for Dark Souls 3 on Windows. I tried using SteamTinkerLaunch last night (but faced reshade download issues, so here I am), but at least got far enough that the ReShade text showed *but on the EasyAntiCheat popup* only. I didn't get GUI in-game, either.

@DieuDeGlace , which version of ReShade did you use, and can you guide a noob to how you got it to work?

**Comment by kevinlekiller** [comment]
If you download the ReShade exe file, you can extract it with the program 7z, `7z x ReShade_Setup_5.0.2.exe` for example.

Among the extracted files you'll find 2 `.dll` files, one called `ReShade64.dll` and one called `ReShade32.dll`, if the game is 64 bit (Elden Ring is, see https://www.pcgamingwiki.com/wiki/Elden_Ring#API) you want to use `ReShade64.dll`, you'll have to rename `ReShade64.dll` to something the game will pick up, since the game is using Direct3D 12 (see aforementioned pcgamingwiki link), you want to name it either `dxgi.dll` or `d3d12.dll`. 

You then drop that file into the game's folder where the main executable file is, which is called `start_protected_game.exe`, according to https://steamdb.info/depot/1245621/

You then launch the game and configure ReShade and set the paths to where your shader files are.

**Comment by humanplayer2** [comment]
Thank you, @kevinlekiller , I'll try that first chance!

**Comment by humanplayer2** [comment]
Ok, it's up and running! ReShade on Elden Ring! Thank you for the excellent script, @kevinlekiller , and for the tip, @DieuDeGlace !

To get it working, I downloaded and ran the `reshade-linux.sh` script, and followed the prompts throughout. I then downloaded ReShade v. 4.9.1 from [this ReShade repository](reshade-linux.sh), extracted the `.exe`, and copied `ReShade64.dll` to the Elden Ring game folder, renamed it `dxgi.dll`, replacing the symlink created by the script. Running the game through Steam with launch option `WINEDLLOVERRIDES="d3dcompiler_47=n;dxgi=n,b" %command%` as provided by the script launches the game with the ReShade text showing *not* on the EasyAntiCheat popup as I previously saw, but in the game itself, where <kbd>Home</kbd> then opens the ReSahde menu.

**Comment by kevinlekiller** [comment]
You can now manually specify a version of ReShade:

`RESHADE_VERSION="4.9.1" ./reshade-linux.sh`

**Comment by DieuDeGlace** [comment]
> I'm setting up reshaders for the first time on Linux---for Elden Ring---having done it only for Dark Souls 3 on Windows. I tried using SteamTinkerLaunch last night (but faced reshade download issues, so here I am), but at least got far enough that the ReShade text showed _but on the EasyAntiCheat popup_ only. I didn't get GUI in-game, either.
> 
> @DieuDeGlace , which version of ReShade did you use, and can you guide a noob to how you got it to work?
 
 sorry for not seeing this earlier, and glad to see you got it working, but yup thats what i had to do. Though I could kinda short cut it since i have two ssds (one with windows the other endeavourOS) so i just had to grab the dxgi.dll from my windows elden ring file and plop it into linux. Also sounds good kevin!
